# Generated by Django 4.0.1 on 2022-03-20 15:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(decimal_places=0, help_text='format: maximum time 9999999999', max_digits=10, verbose_name="Block's timestamp")),
                ('nonce', models.IntegerField(help_text='format: Int', verbose_name='Number Only Once, for mining a block')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required, unique', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_block', to='blockchain.block', unique=True, verbose_name='previous block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.IntegerField(help_text='format: Int', verbose_name='Number Only Once senders count of transactions')),
                ('from_address', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Senders Public Addresss')),
                ('to_address', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Resceivers Public Addresss')),
                ('amount', models.IntegerField(help_text='format: Int', verbose_name="Transaction's amount")),
                ('fee', models.IntegerField(help_text='format: Int', verbose_name="Transaction's fee")),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blockchain.block', verbose_name="Transaction's block")),
            ],
        ),
    ]
